### ISSUE TITLE
Images Editorial Use Only

### ISSUE THREAD

**Issue by andrexicretin** [mmohamedyaser/shutterstock_downloader#2]
Hello mmohamedyaser.
It's me again.
In the case of "Editorial Use Only" images, the script box stopped working.
"box = driver.find_element_by_xpath("//span/span/input[contains(@name, 'EditorialUseOnly')]")"
I tried to fix it using "EC" but it didn't work.

**Comment by mmohamedyaser** [comment]
Hi @andrexicretin,
I have updated the code. It should work well now.
I have to update the code and remove the editor part. 
Shutterstock has removed the old editor two days back. No more high quality images.
